config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "articles#index"
  resources :articles, only: [:index, :new, :create, :show, :destroy] do
    resources :messages, only: [:index, :create]
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show, :edit, :update, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_tags, dependent: :destroy
  has_many :tags, through: :article_tags, dependent: :destroy
  has_many :messages, dependent: :destroy
  
  def self.search(search)
    if search != ""
      Article.where('(title LIKE(?)) OR (text LIKE(?))', "%#{search}%", "%#{search}%")
    end
  end

end

app/models/article_tag.rb
class ArticleTag < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :article
  belongs_to :user
  validates :content, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :article_tags, dependent: :destroy
  has_many :articles, through: :article_tags, dependent: :destroy

  validates :subj, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_one_attached :image, dependent: :destroy
  
  validates :nickname, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?



  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :profile, :image, :fav_subj, :weak_subj])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :new, :destroy, :create]

  def index
    @articles = Article.all.order('created_at DESC').includes(:user).page(params[:page]).per(10)
  end

  def new
    @article = ArticleTagTable.new
  end

  def create
    @article = ArticleTagTable.new(article_params)
    if @article.valid?
       @article.save
       return redirect_to root_path
    else
       render "new"
    end
  end

  def show
    @article = Article.find(params[:id])
    gon.article = @article
    @message = Message.new
    @messages = @article.messages.order('created_at DESC').includes(:user)
    if user_signed_in?
      gon.user = current_user.nickname
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy if current_user == @article.user

    redirect_to root_path
  end

  def search
    if params[:keyword].present?
      @articles = Article.search(params[:keyword]).order('created_at DESC').includes(:user)
    else
      redirect_to root_path
    end
  end



  private

  def article_params
    params.require(:article_tag_table).permit(:text, :title, :subj).merge(user_id: current_user.id)
  end


end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @article = Article.find(params[:article_id])
    @message = @article.messages.new(message_params)
    
    if @message.save
      render json: {message: @message}
    end
  end
end

private

def message_params
  params.require(:message).permit(:content).merge(user_id: current_user.id, article_id: @article.id)
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def show
  end
  
  def edit
    redirect_to root_path if current_user != @user
  end

  def update
    if current_user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def destroy
    if current_user.destroy
      redirect_to root_path
    else
      render :edit
    end
  end


  private
  def user_params
    params.require(:user).permit(:nickname, :profile, :fav_subj, :weak_subj, :image)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/index.html.erb
<div class="container-fluid  article-show">
  <div class="row article-contents">
    <div class="col-2 px-0">
      <div class="nav flex-column nav-pills bg-warning border" id="v-pills-tab" role="tablist" aria-orientation="vertical">
        <a class="nav-link active border" id="v-pills-home-tab" data-toggle="pill" href="#v-pills-home" role="tab" aria-controls="v-pills-home" aria-selected="true">Home</a>
        <a class="nav-link border" id="v-pills-constitution-tab" data-toggle="pill" href="#v-pills-constitution" role="tab" aria-controls="v-pills-constitution" aria-selected="false">憲法</a>
        <a class="nav-link border" id="v-pills-civil-tab" data-toggle="pill" href="#v-pills-civil" role="tab" aria-controls="v-pills-civil" aria-selected="false">民法</a>
        <a class="nav-link border" id="v-pills-criminal-tab" data-toggle="pill" href="#v-pills-criminal" role="tab" aria-controls="v-pills-criminal" aria-selected="false">刑法</a>
        <a class="nav-link border" id="v-pills-civil-procedure-tab" data-toggle="pill" href="#v-pills-civil-procedure" role="tab" aria-controls="v-pills-civil-procedure" aria-selected="false">民事訴訟法</a>
        <a class="nav-link border" id="v-pills-criminal-procedure-tab" data-toggle="pill" href="#v-pills-criminal-procedure" role="tab" aria-controls="v-pills-criminal-procedure" aria-selected="false">刑事訴訟法</a>
        <a class="nav-link border" id="v-pills-administrative-tab" data-toggle="pill" href="#v-pills-administrative" role="tab" aria-controls="v-pills-administrative" aria-selected="false">行政法</a>
      </div>
      <h4>科目更新予定</h4>
    </div>
    <div class="col-10">
      <div class="tab-content" id="v-pills-tabContent">
        <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
          <div class="jumbotron jumbotron-fluid">
            <h1 class="display-4">誰とでも簡単に法律の討論を</h1>
            <p class="lead">今この世の中だからこそ、もっと話そう</p>
            <p class="lead">自分の意見を自由にぶつけられる場が「りーがるゼミ」</p>
          </div>            
          <div class="title text-center">
            <h3>新着投稿</h3>
          </div>
          <div class="row text-break">
            <% if Article.present? %>
              <% @articles.each do |article| %>
                <div class="p-3 col-md-3 text-center">
                  <%= link_to (article_path(article.id)) do %>
                    <% if article.user.image.attached? %>
                      <%= image_tag article.user.image, size: "150x150", class: "rounded-circle img-fluid article-img" %>
                    <% else %>
                      <%= image_tag "avatardefault_92824.png", size: "150x150", class: "rounded-circle img-fluid article-img" %>
                    <% end %>
                    <div class="card">
                      <div class="card-body bg-light">
                        <%= article.title %>
                      </div>
                    </div>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
          <%= paginate @articles, theme: 'twitter-bootstrap-4'%>
        </div>
        <div class="tab-pane fade" id="v-pills-constitution" role="tabpanel" aria-labelledby="v-pills-constitution-tab">
          <div class="title text-center">
            <h3>憲法</h3>
          </div>
          <div class="row text-break">
            <% if Article.present? %>
              <% Tag.where(subj: "憲法").order('created_at DESC').each do |tag| %>
                <div class="p-3 col-md-4 text-center">
                  <% ArticleTag.where(tag_id: tag.id).each do |article_tag| %>
                    <%= link_to (article_path(article_tag.article.id)) do %>
                      <% if article_tag.article.user.image.attached? %>
                        <%= image_tag(article_tag.article.user.image, size: "150x150", class: "rounded-circle img-fluid article-img") %>
                      <% else %>
                        <%= image_tag "avatardefault_92824.png", size: "150x150", class: "rounded-circle img-fluid article-img" %>
                      <% end %>
                      <div class="card">
                        <div class="card-body bg-light text-dark">
                          <%= article_tag.article.title %>
                        </div>
                      </div>
                    <% end %>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="tab-pane fade" id="v-pills-civil" role="tabpanel" aria-labelledby="v-pills-civil-tab">
          <div class="title text-center">
            <h3>民法</h3>
          </div>
          <div class="row text-break">
            <% if Article.present? %>
              <% Tag.where(subj: "民法").order('created_at DESC').each do |tag| %>
                <div class="p-3 col-md-4 text-center">
                  <% ArticleTag.where(tag_id: tag.id).each do |article_tag| %>
                    <%= link_to (article_path(article_tag.article.id)) do %>
                      <% if article_tag.article.user.image.attached? %>
                        <%= image_tag(article_tag.article.user.image, size: "150x150", class: "rounded-circle img-fluid article-img") %>
                      <% else %>
                        <%= image_tag "avatardefault_92824.png", size: "150x150", class: "rounded-circle img-fluid article-img" %>
                      <% end %>
                      <div class="card">
                        <div class="card-body bg-light text-dark">
                          <%= article_tag.article.title %>
                        </div>
                      </div>
                    <% end %>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="tab-pane fade" id="v-pills-criminal" role="tabpanel" aria-labelledby="v-pills-criminal-tab">
          <div class="title text-center">
            <h3>刑法</h3>
          </div>
          <div class="row text-break">
            <% if Article.present? %>
              <% Tag.where(subj: "刑法").order('created_at DESC').each do |tag| %>
                <div class="p-3 col-md-4 text-center">
                  <% ArticleTag.where(tag_id: tag.id).each do |article_tag| %>
                    <%= link_to (article_path(article_tag.article.id)) do %>
                      <% if article_tag.article.user.image.attached? %>
                        <%= image_tag(article_tag.article.user.image, size: "150x150", class: "rounded-circle img-fluid article-img") %>
                      <% else %>
                        <%= image_tag "avatardefault_92824.png", size: "150x150", class: "rounded-circle img-fluid article-img" %>
                      <% end %>
                      <div class="card">
                        <div class="card-body bg-light text-dark">
                          <%= article_tag.article.title %>
                        </div>
                      </div>
                    <% end %>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="tab-pane fade" id="v-pills-civil-procedure" role="tabpanel" aria-labelledby="v-pills-civil-procedure-tab">
          <div class="title text-center">
            <h3>民事訴訟法</h3>
          </div>
          <div class="row text-break">
            <% if Article.present? %>
              <% Tag.where(subj: "民事訴訟法").order('created_at DESC').each do |tag| %>
                <div class="p-3 col-md-4 text-center">
                  <% ArticleTag.where(tag_id: tag.id).each do |article_tag| %>
                    <%= link_to (article_path(article_tag.article.id)) do %>
                      <% if article_tag.article.user.image.attached? %>
                        <%= image_tag(article_tag.article.user.image, size: "150x150", class: "rounded-circle img-fluid article-img") %>
                      <% else %>
                        <%= image_tag "avatardefault_92824.png", size: "150x150", class: "rounded-circle img-fluid article-img" %>
                      <% end %>
                      <div class="card">
                        <div class="card-body bg-light text-dark">
                          <%= article_tag.article.title %>
                        </div>
                      </div>
                    <% end %>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="tab-pane fade" id="v-pills-criminal-procedure" role="tabpanel" aria-labelledby="v-pills-criminal-procedure-tab">
          <div class="title text-center">
            <h3>刑事訴訟法</h3>
          </div>
          <div class="row text-break">
            <% if Article.present? %>
              <% Tag.where(subj: "刑事訴訟法").order('created_at DESC').each do |tag| %>
                <div class="p-3 col-md-4 text-center">
                  <% ArticleTag.where(tag_id: tag.id).each do |article_tag| %>
                    <%= link_to (article_path(article_tag.article.id)) do %>
                      <% if article_tag.article.user.image.attached? %>
                        <%= image_tag(article_tag.article.user.image, size: "150x150", class: "rounded-circle img-fluid article-img") %>
                      <% else %>
                        <%= image_tag "avatardefault_92824.png", size: "150x150", class: "rounded-circle img-fluid article-img" %>
                      <% end %>
                      <div class="card">
                        <div class="card-body bg-light text-dark">
                          <%= article_tag.article.title %>
                        </div>
                      </div>
                    <% end %>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="tab-pane fade" id="v-pills-administrative" role="tabpanel" aria-labelledby="v-pills-administrative-tab">
          <div class="title text-center">
            <h3>行政法</h3>
          </div>
          <div class="row text-break">
            <% if Article.present? %>
              <% Tag.where(subj: "行政法").order('created_at DESC').each do |tag| %>
                <div class="p-3 col-md-4 text-center">
                  <% ArticleTag.where(tag_id: tag.id).each do |article_tag| %>
                    <%= link_to (article_path(article_tag.article.id)) do %>
                      <% if article_tag.article.user.image.attached? %>
                        <%= image_tag(article_tag.article.user.image, size: "150x150", class: "rounded-circle img-fluid article-img") %>
                      <% else %>
                        <%= image_tag "avatardefault_92824.png", size: "150x150", class: "rounded-circle img-fluid article-img" %>
                      <% end %>
                      <div class="card">
                        <div class="card-body bg-light text-dark">
                          <%= article_tag.article.title %>
                        </div>
                      </div>
                    <% end %>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%= link_to(new_article_path, class: 'button') do %>
  <span class='purchase-btn-text text-light'>投　稿</span>
<% end %>

app/views/articles/new.html.erb
<div class="contents row">
  <div class="container">
    <%= form_with model:@article, url: articles_path, local: true do |f|%>
      <div class="tag-field", id='tag-field'>
        <%= f.label :subj, "科目" %><br />
        <%= f.select :subj, [["憲法", "憲法"], ["民法", "民法"], ["刑法", "刑法"], ["民事訴訟法", "民事訴訟法"], ["刑事訴訟法", "刑事訴訟法"], ["行政法", "行政法"]],include_blank: "選択して下さい" %>
      </div>

      <div class="form-group">
        <%= f.label :title, "論点" %><br />
        <%= f.text_area :title, class: "form-control", placeholder: "*必須" %>
      </div>

      <div class="form-group">
        <%= f.label :text, "考察" %><br />
        <%= f.text_area :text, class: "form-control", placeholder: "*必須" %>
      </div>

      <div class="form-group">
        <%= f.submit "保存する", class: "px-5 m-3 btn btn-primary btn-lg" %>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/search.html.erb
<div class="container-fluid vh-100 article-show">
  <div class="title text-center">
    <h3>検索結果</h3>
  </div>
  <div class="row text-break article-contents">
    <% if @articles.present? %>
      <% @articles.each do |article| %>
        <div class="p-3 col-md-3 text-center">
          <%= link_to (article_path(article.id)) do %>
            <% if article.user.image.attached? %>
              <%= image_tag(article.user.image.variant(resize: '150x150'), class: "rounded-circle img-fluid") %>
            <% else %>
              <%= image_tag "avatardefault_92824.png", size: "150x150", class: "rounded-circle img-fluid" %>
            <% end %>
            <div class="card">
              <div class="card-body bg-light">
                <%= article.title %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    <% else %>
      <h2>検索結果はありません</h2>
    <% end %>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container-fluid article-show">
  <div class="row article-contents">
    <% if current_user != @article.user %>
      <div class="col-md-3">
        <%= render partial: 'users/profile', locals: { user: @article.user} %>
      </div>
    <% end %>
    <div class="col-md-6 pb-3">
      <div class="media">
        <div class="media-body">
          <div class="text-center">
            <p class="mt-3 title">論点</p>
          </div>
          <h5 class="bg-light p-3 rounded">
            <%= @article.title %>
          </h5>
          <div class="text-center">
            <p class="mt-3 title">考察</p>
          </div>
          <p class="bg-light p-3 rounded">
            <%= @article.text %>
          </p>
          <% if current_user == @article.user %>
            <div class="text-center ">
              <%= link_to '削除', article_path, method: :delete, data: { confirm: '削除しますか？' }, class:'article-destroy' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col">
      <%= render partial: 'messages/message_page', locals: { article: @article, message: @message } %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>Legalvl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= include_gon %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <header class="header">
      <nav class="navbar navbar-expand-lg navbar-dark">
          <a class="navbar-brand text-light" href="/">りーがるゼミ</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav ">
              <% if user_signed_in? %>
                <%= link_to "Messages", root_path, class: "nav-link text-success" %>
                <%= link_to "MyPage", user_path(current_user), class: "nav-link text-success" %>
                <%= link_to "詳細Serch", root_path, class: "nav-link text-success" %>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link text-success" %>
              <% else %>
                <%= link_to "詳細Serch", root_path, class: "nav-link text-success" %>
                <%= link_to "Login", new_user_session_path, class: "nav-link text-success" %>
                <%= link_to "新規登録", new_user_registration_path, class: "nav-link text-success" %>
              <% end %>
            </div>
              <%= form_with(url: search_articles_path, local: true, method: :get, class: "search-form") do |f| %>
                <%= f.text_field :keyword, placeholder: "単語検索", class: "search-input" %>
                <%= f.submit "検索", class: "search-btn" %>
              <% end %>
          </div>
      </nav>
    </header>
    <%= yield %>
    <footer class="fixed-bottom vh-10 bg-dark text-light">
      <div>portfolio</div>
    </footer>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="message" id="message">
  <div class="upper-message">
    <div class="message-user">
      <%= message.user.nickname %>
    </div>
    <div class="message-date">
      <%= l message.created_at %>
    </div>
  </div>
  <div class="lower-message">
    <div class="message-content" id= "message_content" >
      <%= message.content %>
    </div>
  </div>
</div>

app/views/messages/_message_page.html.erb
<div class="wrapper">
  <div class="chat">
    <div class="chat-header">
        <div class="header-button">
          <%= link_to "Exit", "#" %>
        </div>
    </div>
    <div class="messages" id="messages">
      <%= render partial: 'messages/message', collection: @messages %>
    </div>
    <% if user_signed_in? %>
        <%= form_with model: [article, message], class: 'form', id: "new_article", local: true do |f| %>
          <div class="form-input">
            <%= f.text_area :content, class: 'form-message', placeholder: 'コメントしよう！',id: "message_text_field" %>
          </div>
            <%= f.submit '送信', class: 'form-submit', id: "submit_btn" %>
        <% end %>
    <% end %>
  </div>
</div>

app/views/users/_profile.html.erb
  <table class="table">
    <tbody>
      <div class="text-center py-5">
        <% if user.image.attached? %>
          <%= link_to image_tag(user.image.variant(resize: '150x150'), class: "rounded-circle img-fluid"), user_path(user.id) %>
        <% else %>
          <%= link_to image_tag("avatardefault_92824.png", size: "150x150", class: "rounded-circle img-fluid"), user_path(user.id) %>
        <% end %>
      </div>
      <tr>
        <th class="table-col1">NickName</th>
        <td class="table-col2"><%= user.nickname %></td>
      </tr>
      <tr>
        <th class="table-col1">Profile</th>
        <td class="table-col2"><%= user.profile %></td>
      </tr>
      <tr>
        <th class="table-col1">得意科目</th>
        <td class="table-col2"><%= user.fav_subj %></td>
      </tr>
      <tr>
        <th class="table-col1">苦手科目</th>
        <td class="table-col2"><%= user.weak_subj %></td>
      </tr>
    </tbody>
  </table>

app/views/users/edit.html.erb
<div class="contents row">
  <div class="container">
  <%= form_with model: @user, class: "new_user", local: true do |f|%>
    <h2>
      <%= "Edit Page" %>
    </h2>
    <%= render 'devise/shared/error_messages', model: @user %>          
    <table class="table text-break">
      <tbody>
        <div class="text-center my-5">
          <% if @user.image.attached? %>
            <%= image_tag(@user.image.variant(resize: '150x150'), class: "rounded-circle img-fluid") %>
          <% else %>
            <%= image_tag "avatardefault_92824.png", size: "150x150", class: "rounded-circle img-fluid" %>
          <% end %>
        </div>
        <tr>
          <th class="form-group table-col1">アイコン画像</th>
          <td class="table-col2"><%= f.file_field :image %></td>
        </tr>
        <tr>
          <th class="table-col1">Nickname</th>
          <td class="table-col2 "><%= f.text_field :nickname%></td>
        </tr>
        <tr>
          <th class="table-col1">Profile</th>
          <td class="table-col2"><%= f.text_area :profile %></td>
        </tr>
        <tr>
          <th class="table-col1"><%= f.label :fav_subj, "得意科目" %></th>
          <td class="table-col2"><%= f.select :fav_subj, [["憲法", "憲法"], ["民法", "民法"], ["刑法", "刑法"], ["民事訴訟法", "民事訴訟法"], ["刑事訴訟法", "刑事訴訟法"], ["行政法", "行政法"]],include_blank: "なし" %></td>
        </tr>
        <tr>
          <th class="table-col1"><%= f.label :weak_subj, "苦手科目" %></th>
          <td class="table-col2"><%= f.select :weak_subj, [["憲法", "憲法"], ["民法", "民法"], ["刑法", "刑法"], ["民事訴訟法", "民事訴訟法"], ["刑事訴訟法", "刑事訴訟法"], ["行政法", "行政法"]],include_blank: "なし" %></td>
        </tr>
      </tbody>
    </table>
    <div class="text-center">
      <% if user_signed_in? && current_user == @user %>
        <%= f.submit "O K", class: "px-5 m-3 btn btn-primary btn-lg"%>    
      <% end %>
      <%= link_to (user_path(current_user))do %>  
        <button class="px-5 m-3 btn btn-primary btn-lg">
          Back
        </button>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="contents row">
  <div class="col-sm-9 container justify-content-center text-break ">
    <%= render partial: 'profile', locals: { user: @user } %>
    <div class="text-center">
      <% if user_signed_in? && current_user == @user %>
        <%= link_to (edit_user_path) do %>  
          <button class="px-5 m-3 btn btn-primary btn-lg">
            Edit
          </button>
        <% end %>
        <%= link_to (user_path(current_user.id)), method: :delete, data: { confirm: '削除しますか？' } do %>  
          <button class="px-5 m-3 btn btn-danger btn-lg">
            Delete
          </button>
        <% end %>
      <% end %>
      <%= link_to (:back) do %>  
        <button class="px-5 m-3 btn btn-primary btn-lg">
          Back
        </button>
      <% end %>
    </div>
  </div>
</div>